# STA130 TUT 02 (Sep13)<br><br> 👨‍💻 👩🏻‍💻 <u>Coding with data types, for loops, and logical control<u>



## ♻️ 📚 Review / Questions [10 minutes]
1. Follow up questions and clarifications regarding regarding **notebooks, markdown, ChatBots, or `Python` code** previously introduced in the Sep06 TUT and Sep09 LEC 

> 1. We're continuing to dive into using **notebooks, markdown**, and `Python` as a tool: building comfort and capability working with **ChatBots** to leverage `Python` code is the objective of the current phase of the course...<br><br>
>
> 2. *Questions about [HW01](https://github.com/pointOfive/stat130chat130/blob/main/HW/STA130F24_HW01_DueSep12.ipynb) which was due yesterday (Thursday Sep12) should be asked in OH from 4-6PM ET Tuesday, Wednesday, and Thursday (see the [Quercus course homepage](https://q.utoronto.ca/courses/354091) for further details)*<br><br>
> 
> 3. *And same story, and even moreso for questions about [HW02](https://github.com/pointOfive/stat130chat130/blob/main/HW/STA130F24_HW02_DueSep19.ipynb) which was due next Thursday (Sep19) (e.g., regarding the "pre-lecture" questions...)*

## 🚧 🏗️ Demo (using Jupyter Notebook and ChatBots) [50 minutes]


#### 1. **[35 of the 50 minutes]** Demonstrate some traditional `python` coding structures

1. `tuple()`, `list()`, vs `dict()  # immutable and mutable "lists" vs key-value pairs`<br><br>
    
2. some `NumPy` functions:<br><br>
    
    1. `import numpy as np`
    2. `np.array([1,2,3]) # a faster "list"`
    3. `np.random.choice([1,2,3])`<br><br>
        
3. `for i in range(n):`, `for x in a_list:`, `for i,x in enumerate(a_list):`, and `print()`<br><br>
    
    1. `variable` as the last line of a "code cell" in a notebook "prints" the value
    2. but `print()` is needed inside `for` loop if you want to output something<br><br>
        
4. `if`/`else` conditional statements<br><br> 

    1. perhaps with `x in b_list`<br>or `i % 2 == 0` to treat evens/odds differently  (sort of like the infamous "FizzBuzz" problem that some people [can't complete](https://www.quora.com/On-average-what-is-the-proportion-of-applicants-that-cannot-pass-a-simple-FizzBuzz-test-based-on-your-personal-experience-or-on-facts) as part of a coding interview challenge)
    2. note the "similarity" to the `try-except` block structure when that's encountered in the code below since it's used there (despite being a "more advanced" 
        
#### 2. **[5 of the 50 minutes]** Reintroduce the [Monty Hall problem](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/GPT/SLS/00001_gpt3p5_MonteHall_ProblemExplanation_v1.md) and see which of the coding structures above you recognize (or do not see) in the Monty Hall simulation code below

#### 3. **[10 of the 50 minutes]** Use any remaining time to start a demonstration of using a ChatBot to (a) understand what the code below is doing and (b) suggest an improved streamlined version of the `for` loop simulation code that might be easier to explain and understand
    
> ChatGPT version 3.5 [was very effective](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/GPT/SLS/00003_gpt3p5_MonteHall_CodeDiscussion_v1.md) for (b), while Copilot was shockingly bad on a [first try](../CHATLOG/wk2/COP/SLS/00001_creative_MonteHall_CodeDiscussion_v1.md) but was able to do better [with some helpful guidance](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/COP/SLS/00002_concise_MonteHall_CodeDiscussion_v2.md).

# Tuple Example 

In [1]:
# Cell to demo what the above code does
# Creating a tuple
my_tuple = (10, 20, 30, 'apple')

# Accessing elements (indexing)
print(my_tuple[0])  # Output: 10

# Can iterate through a tuple
for item in my_tuple:
    print(item)

10
10
20
30
apple


In [2]:
# Tuples are immutable
my_tuple[0] = 100  # This will raise a TypeError

TypeError: 'tuple' object does not support item assignment

# Lists

In [5]:
# Add more code cells to keep a record of the demos
# Creating a list
my_list = [10, 20, 30, 'banana']

# Accessing elements (indexing)
print(my_list[0])  # Output: 10

# Lists are mutable
my_list[0] = 100
print(my_list)  # Output: [100, 20, 30, 'banana']

# Adding elements
my_list.append('grape')
print(my_list)

# Removing elements
my_list.append(30)
my_list.append(30)
print(my_list)
my_list.remove(30)


print(my_list)  # Output: [100, 20, 'banana', 'grape']


10
[100, 20, 30, 'banana']
[100, 20, 30, 'banana', 'grape']
[100, 20, 30, 'banana', 'grape', 30, 30]
[100, 20, 'banana', 'grape', 30, 30]


The reason why the following code did not delete all "30" inputs is that the remove() method in Python removes only the first occurrence of the specified value from the list. It does not remove all instances of that value.

# Dict

In [8]:
# Creating a dictionary
my_dict_person = {'name': 'Alice', 'age': 25, 'city': 'New York'}

# Accessing elements (by key)
print(my_dict_person['name'])  # Output: Alice

# Dictionaries are mutable
my_dict_person['age'] = 26
print(my_dict_person)  # Output: {'name': 'Alice', 'age': 26, 'city': 'New York'}

# Adding new key-value pairs
my_dict_person['country'] = 'USA'
print(my_dict_person)

# Removing key-value pairs
del my_dict_person['city']

print(my_dict_person)  # Output: {'name': 'Alice', 'age': 26, 'country': 'USA'}


Alice
{'name': 'Alice', 'age': 26, 'city': 'New York'}
{'name': 'Alice', 'age': 26, 'city': 'New York', 'country': 'USA'}
{'name': 'Alice', 'age': 26, 'country': 'USA'}


# Numpy 

NumPy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is essential for scientific computing, enabling fast operations on arrays (e.g., element-wise operations, linear algebra, random sampling) and serves as the foundation for other data science libraries like pandas, SciPy, and TensorFlow.

### Key Uses:
- Efficient array manipulation.
- Mathematical and statistical operations.
- Handling multidimensional data.
- Integration with other scientific libraries.

In [10]:
# 1. Importing NumPy
import numpy as np

In [12]:
# 2. Creating Arrays
#Creating a 1D array (vector):
arr = np.array([1, 2, 3, 4, 5])
arr # what is a difference between list and array 

array([1, 2, 3, 4, 5])

In [14]:
#2.Creating a 2D array (matrix):
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[[1 2 3]
 [4 5 6]]


In [15]:
matrix = np.array([[1, 2], [4, 5, 6]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Array Operations

In [16]:
arr = np.array([1, 2, 3, 4])
print(arr + 5)  # Output: [6 7 8 9]
print(arr * 2)  # Output: [2 4 6 8]


[6 7 8 9]
[2 4 6 8]


.... Refere to link for gpt 

# loops 

1. for i in range(n):
This is a loop that runs n times, where i takes values from 0 to n-1.
range(n) generates a sequence of numbers from 0 to n-1.

In [17]:
n = 5
for i in range(n):
    print(i)


0
1
2
3
4


In [20]:
a_list = [10, 20, 30]
for x in a_list:
    print(x)


10
20
30


In [18]:
range(n)

range(0, 5)

In [22]:
a_list = ['apple', 'banana', 'cherry']
for idx, item in enumerate(a_list):
    print(idx, item)


0 apple
1 banana
2 cherry


# if/else conditional statements

In [23]:
# Assign a value to a variable
number = 10

# If/else conditional statement
if number > 0: 
    print("The number is positive")
elif number == 0:
    print("The number is zero")
else:
    print("The number is negative")


The number is positive


In [24]:
# Assign a value to a variable 
# Not a logical example 
number = 10

# If/else conditional statement
if False: 
    print("The number is positive")
elif False:
    print("The number is zero")
else:
    print("The number is negative")

The number is negative


In [1]:
# Monte Hall Simulation Code -- not the only way to code this, but it's what Prof. Schwartz came up with...

import numpy as np
all_door_options = (1,2,3)  # tuple
my_door_choice = 1  # 1,2,3
i_won = 0
reps = 100000
for i in range(reps):
    secret_winning_door = np.random.choice(all_door_options)
    all_door_options_list = list(all_door_options)
    # take the secret_winning_door, so we don't show it as a "goat" losing door
    all_door_options_list.remove(secret_winning_door)
    try:
        # if my_door_choice was secret_winning_door then it's already removed
        all_door_options_list.remove(my_door_choice)
    except:
        pass
    # show a "goat" losing door and remove it
    goat_door_reveal = np.random.choice(all_door_options_list)
    all_door_options_list.remove(goat_door_reveal)

    # put the secret_winning_door back in if it wasn't our choice
    # we previously removed it, so it would be shown as a  "goat" losing door
    if secret_winning_door != my_door_choice:
        all_door_options_list.append(secret_winning_door)
    # if secret_winning_door was our choice then all that's left in the list is a "goat" losing door
    # if secret_winning_door wasn't our choice then it's all that will be left in the list

    # swap strategy
    my_door_choice = all_door_options_list[0]

    if my_door_choice == secret_winning_door:
        i_won += 1

i_won/reps

0.66777

Let's break it down into smaller steps to make it easier to follow.

### Overview of the Monty Hall Problem:
Imagine you're on a game show, and you're asked to choose one of three doors. Behind one door is a car (the prize), and behind the other two are goats. After you choose a door, the host (Monty) will open one of the remaining doors, revealing a goat. You are then given the option to **stay** with your original choice or **switch** to the other unopened door.

The counterintuitive result is that you're more likely to win if you **switch** (your probability of winning by switching is 2/3).

Now let's walk through the code step by step.

---

### Step 1: Importing Libraries and Initial Setup

```python
import numpy as np
all_door_options = (1, 2, 3)  # Tuple representing three doors (1, 2, 3)
my_door_choice = 1  # You always start by choosing door 1
i_won = 0  # Count of how many times you win by switching doors
reps = 100000  # Number of times to repeat the simulation (100,000)
```
- **`all_door_options`**: This is a tuple that represents the three doors available to choose from (1, 2, 3).
- **`my_door_choice`**: You initially always pick door 1.
- **`i_won`**: This variable keeps track of how many times you win by switching doors.
- **`reps`**: The number of repetitions for the simulation (100,000 times in this case).

---

### Step 2: Running the Simulation Multiple Times

```python
for i in range(reps):
    secret_winning_door = np.random.choice(all_door_options)  # Randomly pick the winning door
```
- This loop runs the simulation 100,000 times (`reps = 100000`).
- For each iteration, the game randomly selects which door hides the car (`secret_winning_door`).

---

### Step 3: Removing Doors to Simulate Monty Hall's Behavior

```python
    all_door_options_list = list(all_door_options)  # Convert tuple to list to remove doors
    all_door_options_list.remove(secret_winning_door)  # Remove the winning door
```
- Convert the tuple of doors into a list so that we can modify it (remove doors).
- Remove the door with the car (`secret_winning_door`) because Monty won't reveal the prize.

---

### Step 4: Remove Player’s Initial Choice

```python
    try:
        all_door_options_list.remove(my_door_choice)  # Remove the player's initial choice
    except:
        pass  # Ignore errors if the player's choice is already removed
```
- If the player's initial choice is the same as the winning door, we remove it from the list.
- The `try` block handles the case where the player's choice was already removed (if they picked the winning door initially).

---

### Step 5: Monty Reveals a Goat Door

```python
    goat_door_reveal = np.random.choice(all_door_options_list)  # Monty reveals a goat
    all_door_options_list.remove(goat_door_reveal)  # Remove the goat door from the list
```
- Monty randomly selects one of the remaining doors to reveal a goat (`goat_door_reveal`).
- That goat door is then removed from the list, leaving only the player's choice and one other door.

---

### Step 6: Player Switches to the Remaining Door

```python
    if secret_winning_door != my_door_choice:
        all_door_options_list.append(secret_winning_door)  # Add back the winning door if needed
    my_door_choice = all_door_options_list[0]  # Player switches to the remaining door
```
- If the player's original choice wasn't the winning door, we add the winning door back to the list.
- The player then switches to the only remaining door (`my_door_choice = all_door_options_list[0]`).

---

### Step 7: Check if Player Wins

```python
    if my_door_choice == secret_winning_door:
        i_won += 1  # Increment the win counter if the player wins
```
- After switching, if the player's new door is the winning door, they win, and `i_won` is incremented.

---

### Step 8: Calculate the Win Rate

```python
i_won / reps  # Calculate the win percentage by dividing wins by the total repetitions
```
- At the end, the win rate is calculated by dividing the number of wins (`i_won`) by the total number of simulations (`reps`).

---

### Simplified Summary:

1. The player always chooses door 1.
2. The winning door is randomly chosen.
3. Monty reveals a losing (goat) door.
4. The player switches to the remaining door.
5. If the new door is the winning door, the player wins.
6. This is repeated 100,000 times to estimate the probability of winning by switching.

The result (`i_won / reps`) will show that switching doors leads to a win around 66.6% of the time, which aligns with the Monty Hall problem's solution.

I hope this step-by-step explanation makes the code easier to follow!

link of gpt : https://chatgpt.com/share/66e48cd2-bd6c-8002-81cf-3e6234daa5a5

## 💬 🗣️ Communication [40 minutes]
    
#### 1. **[5 of the 40 minutes]** Quickly execute the "rule of 5" and take 5 minutes to break into 5 new groups of about 5 students and assign the following 5 questions to the 5 groups (and note that this instruction uses fives 5's 😉). Consider allowing students to preferentially select which group they join by calling for volunteers for each prompt, and feel free to use 5 minutes from the next (dicussion) sections doing so if you choose to (since this could be viewed as being a part of the "discussion").

> *For each of the prompts, groups should consider the pros and cons of two options, the potential impact of a decision to persue one of the options, and how they take into account how uncertainty influences their thinking about the options.<br><br>*
>
> <details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>
>     
> I asked a ChatBot to create a group activity for you that was related to decision-making under uncertainty using probability, and it produced the following questions. 
> 
> *This is a little bit like one of the ideas in the "Afterward" of HW01 asking a ChatBot to suggest and explain some other, perhaps less well-known "unintuitive surprising statistics paradoxes" (besides the "World War 2 Plane" and "Monte Hall" problems)*
>
> </details>

1. **Stock Investment Strategy:** Students are investors trying to maximize their returns in the stock market. They must decide between two investment strategies: "diversified portfolio" or "focused portfolio." Each strategy has different probabilities of success based on market conditions.<br><br>
    
    1. Diversified Portfolio: Spread investments across multiple industries.
    2. Focused Portfolio: Concentrate investments in a few high-potential stocks.<br><br>
        
2. **Healthcare Treatment Decision:** Students are healthcare professionals deciding between two treatment options for a patient's condition. Each treatment has different success rates and potential side effects.<br><br>
    
    1. Treatment A: High success rate but moderate side effects.
    2. Treatment B: Lower success rate but minimal side effects.<br><br>
        
3. **Sports Team Strategy:** Students are coaches of a sports team planning their game strategy. They must decide between two tactics: "offensive strategy" or "defensive strategy." Each strategy has different probabilities of winning based on the opponent's strengths and weaknesses.<br><br>
    
    1. Offensive Strategy: Focus on scoring goals/points aggressively.
    2. Defensive Strategy: Prioritize defense to prevent the opponent from scoring.<br><br>
        
4. **Career Path Decision:** Students are recent graduates deciding between two career paths: "corporate job" or "entrepreneurship." Each path has different probabilities of success and factors to consider, such as job security, income potential, and work-life balance.<br><br>
    
    1. Corporate Job: Stable income but limited growth opportunities.
    2. Entrepreneurship: Higher potential for success but greater risk and uncertainty.<br><br>
        
5. **Environmental Conservation Strategy:** Students are environmental activists advocating for conservation efforts in a wildlife reserve. They must decide between two conservation strategies: "habitat preservation" or "species reintroduction." Each strategy has different probabilities of achieving long-term sustainability for the ecosystem.<br><br>
    
    1. Habitat Preservation: Protect existing habitats from human encroachment.
    2. Species Reintroduction: Reintroduce endangered species to restore ecological balance.


#### 2. **[15 to 20 of the 40 minutes]** Each group plans and prepares a brief (approximately 3 minute) summary (a) introducing their problem context and (b) outlining their decision and the rationale behind it. The group presentations should address

1. the expected outcomes of their decision
2. the risks involved
3. and why they believe their choice is the best in light of their characterization of the degree uncertainty present in their context 

#### 3. **[15 to 20 of the 40 minutes]** Each group gives their (approximately 3 minute) planned presentation. If time permits, engaging in some (students or TA) Q&A seeking clarification or challenging group decisions would be ideal.

Groups who manage to plan a presentation where multiple group members actively part of the presentation should be awarded "gold stars", figuratively, of course, since actualy gold, or stars, of gold star stickers are unfortunately momentarily in short supply